# Generated by Django 5.1.7 on 2025-04-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_image',
        ),
    ]
