# Generated by Django 5.1.7 on 2025-04-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0002_remove_customuser_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
