# Generated by Django 5.1.7 on 2025-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0003_customuser_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
    ]
