# Generated by Django 5.1.7 on 2025-04-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0005_alter_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
