# Generated by Django 5.1.7 on 2025-04-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0006_alter_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
